remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Uber Fare Dataset Analysis by Group34]
description: [This is a basic data analysis of Uber Fare Analysis]